"""Add has_completed_assessment to users

Revision ID: 5561cf2f5816
Revises: 2c205a019f61
Create Date: 2025-09-24 16:42:19.167361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5561cf2f5816'
down_revision = '2c205a019f61'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('has_completed_assessment', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'has_completed_assessment')
    # ### end Alembic commands ###
