"""Add assessment tables

Revision ID: cfaeb960aa08
Revises: 5561cf2f5816
Create Date: 2025-09-26 09:56:24.913620

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cfaeb960aa08'
down_revision = '5561cf2f5816'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('subtopic', sa.String(), nullable=True),
    sa.Column('grade_level', sa.String(), nullable=False),
    sa.Column('difficulty_order', sa.Integer(), nullable=True),
    sa.Column('prerequisites', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('learning_objectives', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_areas_id'), 'knowledge_areas', ['id'], unique=False)
    op.create_table('assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('grade_level', sa.String(), nullable=False),
    sa.Column('assessment_type', sa.String(), nullable=False),
    sa.Column('difficulty_level', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=True),
    sa.Column('questions_answered', sa.Integer(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('time_taken', sa.Integer(), nullable=True),
    sa.Column('knowledge_gaps', sa.JSON(), nullable=True),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessments_id'), 'assessments', ['id'], unique=False)
    op.create_table('student_knowledge_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('knowledge_area_id', sa.Integer(), nullable=False),
    sa.Column('mastery_level', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('last_assessed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assessment_count', sa.Integer(), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['knowledge_area_id'], ['knowledge_areas.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_knowledge_profiles_id'), 'student_knowledge_profiles', ['id'], unique=False)
    op.create_table('assessment_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('subtopic', sa.String(), nullable=True),
    sa.Column('difficulty_level', sa.String(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=False),
    sa.Column('student_answer', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('time_taken', sa.Integer(), nullable=True),
    sa.Column('ai_feedback', sa.Text(), nullable=True),
    sa.Column('hints_used', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_questions_id'), 'assessment_questions', ['id'], unique=False)
    op.add_column('lessons', sa.Column('knowledge_area_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'lessons', 'knowledge_areas', ['knowledge_area_id'], ['id'])
    op.add_column('study_plan_lessons', sa.Column('title', sa.String(), nullable=False))
    op.add_column('study_plan_lessons', sa.Column('knowledge_area_id', sa.Integer(), nullable=True))
    op.add_column('study_plan_lessons', sa.Column('suggested_duration_mins', sa.Integer(), nullable=True))
    op.add_column('study_plan_lessons', sa.Column('week', sa.Integer(), nullable=True))
    op.add_column('study_plan_lessons', sa.Column('details', sa.Text(), nullable=True))
    op.add_column('study_plan_lessons', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('study_plan_lessons', 'lesson_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'study_plan_lessons', 'knowledge_areas', ['knowledge_area_id'], ['id'])
    op.drop_column('study_plan_lessons', 'order_index')
    op.drop_column('study_plan_lessons', 'completed_at')
    op.drop_column('study_plan_lessons', 'is_completed')
    op.add_column('study_plans', sa.Column('assessment_id', sa.Integer(), nullable=True))
    op.add_column('study_plans', sa.Column('title', sa.String(), nullable=False))
    op.add_column('study_plans', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('study_plans', sa.Column('meta', sa.JSON(), nullable=True))
    op.create_foreign_key(None, 'study_plans', 'assessments', ['assessment_id'], ['id'])
    op.drop_column('study_plans', 'description')
    op.drop_column('study_plans', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_plans', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('study_plans', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'study_plans', type_='foreignkey')
    op.drop_column('study_plans', 'meta')
    op.drop_column('study_plans', 'summary')
    op.drop_column('study_plans', 'title')
    op.drop_column('study_plans', 'assessment_id')
    op.add_column('study_plan_lessons', sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('study_plan_lessons', sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('study_plan_lessons', sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'study_plan_lessons', type_='foreignkey')
    op.alter_column('study_plan_lessons', 'lesson_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('study_plan_lessons', 'created_at')
    op.drop_column('study_plan_lessons', 'details')
    op.drop_column('study_plan_lessons', 'week')
    op.drop_column('study_plan_lessons', 'suggested_duration_mins')
    op.drop_column('study_plan_lessons', 'knowledge_area_id')
    op.drop_column('study_plan_lessons', 'title')
    op.drop_constraint(None, 'lessons', type_='foreignkey')
    op.drop_column('lessons', 'knowledge_area_id')
    op.drop_index(op.f('ix_assessment_questions_id'), table_name='assessment_questions')
    op.drop_table('assessment_questions')
    op.drop_index(op.f('ix_student_knowledge_profiles_id'), table_name='student_knowledge_profiles')
    op.drop_table('student_knowledge_profiles')
    op.drop_index(op.f('ix_assessments_id'), table_name='assessments')
    op.drop_table('assessments')
    op.drop_index(op.f('ix_knowledge_areas_id'), table_name='knowledge_areas')
    op.drop_table('knowledge_areas')
    # ### end Alembic commands ###
