"""add learning profile fields

Revision ID: manual_add_learning_profile_fields
Revises: eb17a948b9f7
Create Date: 2026-01-19 08:10:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'manual_add_learning_profile_fields'
down_revision = 'eb17a948b9f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_profiles', sa.Column('interests', sa.JSON(), nullable=True))
    op.add_column('student_profiles', sa.Column('preferred_format', sa.String(), nullable=True))
    op.add_column('student_profiles', sa.Column('preferred_session_length', sa.Integer(), nullable=True))
    op.add_column('student_profiles', sa.Column('profile_completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_profiles', 'profile_completed')
    op.drop_column('student_profiles', 'preferred_session_length')
    op.drop_column('student_profiles', 'preferred_format')
    op.drop_column('student_profiles', 'interests')
    # ### end Alembic commands ###